BEGIN;

INSERT INTO "Estados" ("ESTADOS_ID", "ESTADOS_NOME")
SELECT 910, 'Estado Teste API'
WHERE NOT EXISTS (SELECT 1 FROM "Estados" WHERE "ESTADOS_ID" = 910);

INSERT INTO "Cidades" ("CIDADES_ID", "CIDADES_NOME")
SELECT 910, 'Cidade Teste API'
WHERE NOT EXISTS (SELECT 1 FROM "Cidades" WHERE "CIDADES_ID" = 910);

INSERT INTO "Localizacao" ("LOCAL_ID", "LOCAL_CEP", "Estados_ESTADOS_ID", "Cidades_CIDADES_ID")
SELECT 910, '01001-000', 910, 910
WHERE NOT EXISTS (SELECT 1 FROM "Localizacao" WHERE "LOCAL_ID" = 910);

INSERT INTO "BANCOS" ("BANCOS_ID", "BANCOS_NOME")
SELECT 910, 'Banco Teste API'
WHERE NOT EXISTS (SELECT 1 FROM "BANCOS" WHERE "BANCOS_ID" = 910);

INSERT INTO "Tipo_Contas" ("TIPOCONTAS_ID", "TIPOCONTAS_NOME")
SELECT 910, 'Conta Teste API'
WHERE NOT EXISTS (SELECT 1 FROM "Tipo_Contas" WHERE "TIPOCONTAS_ID" = 910);

INSERT INTO "Categoria" ("CAT_ID", "CAT_TIPO", "CAT_NOME", "CAT_DESCRICAO")
OVERRIDING SYSTEM VALUE
SELECT 9101, 'DESPESA', 'Categoria Teste API', 'Categoria criada para teste'
WHERE NOT EXISTS (SELECT 1 FROM "Categoria" WHERE "CAT_ID" = 9101);

INSERT INTO "TIPO_TRANSACAO" ("TIPO_TRANSACAO_ID", "TIPO_TRANSACAO_NOME", "TIPO_TRANSACAO_DESCRICAO")
OVERRIDING SYSTEM VALUE
SELECT 9101, 'PIX TESTE', 'Tipo de transacao para teste'
WHERE NOT EXISTS (SELECT 1 FROM "TIPO_TRANSACAO" WHERE "TIPO_TRANSACAO_ID" = 9101);

INSERT INTO "Usuario" ("USU_ID", "USU_NOME", "USU_CPF", "USU_EMAIL", "USU_SENHA", "USU_TEL", "Localizacao_LOCAL_ID")
OVERRIDING SYSTEM VALUE
SELECT 9101, 'Usuario Teste API', '99999999991', 'usuario9101@teste.com', '123456', '11999999101', 910
WHERE NOT EXISTS (SELECT 1 FROM "Usuario" WHERE "USU_ID" = 9101);

INSERT INTO "Contas" ("CONTAS_ID", "CONTAS_NOME", "CONTAS_SALDO_INICIAL", "Usuario_USU_ID", "BANCOS_BANCOS_ID", "Tipo_Contas_TIPOCONTAS_ID")
OVERRIDING SYSTEM VALUE
SELECT 9101, 'Conta Teste API', 1500.00, 9101, 910, 910
WHERE NOT EXISTS (SELECT 1 FROM "Contas" WHERE "CONTAS_ID" = 9101);

INSERT INTO "Metas" ("METAS_ID", "METAS_NOME", "METAS_VALOR_OBJETIVO", "METAS_VALOR_ATUAL", "METAS_DATA_LIMITE", "Usuario_USU_ID")
SELECT 9101, 'Meta Teste API', 5000.00, 250.00, DATE '2026-12-31', 9101
WHERE NOT EXISTS (SELECT 1 FROM "Metas" WHERE "METAS_ID" = 9101);

INSERT INTO "Cartoes" ("CARTOES_ID", "CARTOES_NOME", "CARTOES_LIMITE", "CARTOES_FECHAMENTO", "CARTOES_VENCIMENTO", "Usuario_USU_ID")
OVERRIDING SYSTEM VALUE
SELECT 9101, 'Cartao Teste API', 3000.00, DATE '2026-04-10', DATE '2026-04-20', 9101
WHERE NOT EXISTS (SELECT 1 FROM "Cartoes" WHERE "CARTOES_ID" = 9101);

INSERT INTO "Transacao" ("TRANS_ID", "TRANS_VALOR", "TRANS_DESCRICAO", "TRANS_DATAMOVIMENTACAO", "Categoria_CAT_ID", "Usuario_USU_ID", "TIPO_TRANSACAO_TIPO_TRANSACAO_ID", "Contas_CONTAS_ID")
OVERRIDING SYSTEM VALUE
SELECT 9101, 89.90, 'Compra teste API', DATE '2026-04-16', 9101, 9101, 9101, 9101
WHERE NOT EXISTS (SELECT 1 FROM "Transacao" WHERE "TRANS_ID" = 9101);

UPDATE "Usuario"
SET "USU_NOME" = 'Usuario Teste API Atualizado'
WHERE "USU_ID" = 9101;

UPDATE "Contas"
SET "CONTAS_SALDO_INICIAL" = 4321.00
WHERE "CONTAS_ID" = 9101;

DELETE FROM "Transacao"
WHERE "TRANS_ID" = 9101;

COMMIT;

SELECT 'USUARIO' AS tabela, "USU_ID" AS id, "USU_NOME" AS dado
FROM "Usuario" WHERE "USU_ID" = 9101
UNION ALL
SELECT 'CONTA', "CONTAS_ID", "CONTAS_NOME" || ' | saldo=' || "CONTAS_SALDO_INICIAL"::text
FROM "Contas" WHERE "CONTAS_ID" = 9101
UNION ALL
SELECT 'META', "METAS_ID", "METAS_NOME" || ' | atual=' || "METAS_VALOR_ATUAL"::text
FROM "Metas" WHERE "METAS_ID" = 9101
UNION ALL
SELECT 'CARTAO', "CARTOES_ID", "CARTOES_NOME"
FROM "Cartoes" WHERE "CARTOES_ID" = 9101;

SELECT COUNT(*) AS transacao_deletada_deve_ser_0
FROM "Transacao"
WHERE "TRANS_ID" = 9101;
