spring.application.name=Sistema_Gerenciador_Financeiro
spring.datasource.url=jdbc:postgresql://localhost/mydb
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.jpa.hibernate.ddl-auto=none
spring.jpa.packages-to-scan=Model.Entidades
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
